apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: data
          emptyDir: { }
      containers:
        - name: postgresql
          image: postgres:9.6.5
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: db.user.name
                  name: db-security
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db.user.password
                  name: db-security
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: postgres.db.name
                  name: postgres-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/
              name: data

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql
  type: LoadBalancer