apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shedlock-hazelcast-scheduler
    version: 0.0.1-SNAPSHOT
  name: shedlock-hazelcast-scheduler
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: shedlock-hazelcast-scheduler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shedlock-hazelcast-scheduler
        version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - image: amsidhmicroservice/shedlock-hazelcast-scheduler:latest
          imagePullPolicy: Always
          name: shedlock-hazelcast-scheduler
          ports:
            - name: liveness-port
              containerPort: 8080
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shedlock-hazelcast-scheduler
    version: 0.0.1-SNAPSHOT
  name: shedlock-hazelcast-scheduler
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: shedlock-hazelcast-scheduler
    version: 0.0.1-SNAPSHOT
  type: LoadBalancer