apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springbootschedulerexample
    version: 0.0.1-SNAPSHOT
  name: springbootschedulerexample
  namespace: default
spec:
  replicas: 5
  minReadySeconds: 45
  selector:
    matchLabels:
      app: springbootschedulerexample
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springbootschedulerexample
        version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - image: amsidhmicroservice/shedlock-scheduler:latest
          imagePullPolicy: Always
          name: springbootschedulerexample
          ports:
            - name: liveness-port
              containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: 34.134.180.29
            - name: POSTGRES_DB
              value: shedlock_db
            - name: POSTGRES_USER
              value: shedlock
            - name: POSTGRES_PASSWORD
              value: shedlock
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbootschedulerexample
    version: 0.0.1-SNAPSHOT
  name: springbootschedulerexample
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: springbootschedulerexample
    version: 0.0.1-SNAPSHOT
  type: LoadBalancer